### ISSUE TITLE
Third party/supplier provided oss disclosure document

### ISSUE THREAD

**Issue by Raghavendra-BJ** [todogroup/osposurvey#100]
Add questions about How does the oss disclosure document supplied by third party vendor is verified in the organisation wrt it's contents and quality

**Comment by anajsana** [comment]
Hi @Raghavendra-BJ ! in which section from the `questions.md` file would add this question? I think that `Part 7: Licensing, Compliance, and Repos`is the best fit. If that's the case, could you please add this issue as a comment in the PR file (line 420)? https://github.com/todogroup/osposurvey/pull/99/files

**Comment by Raghavendra-BJ** [comment]
Hello @anajsana, Thank you, Always happy to be part of the community

Yes, it would make sense in adding this question in part 7

Added this issue as comment

**Comment by anajsana** [comment]
@Raghavendra-BJ sorry, I can's see your comment in the file: https://github.com/todogroup/osposurvey/pull/99/files

Is your comment stated as `pending` by any chance? if so, you need to make your comment public for everyone in the **review changes** green button on the top right corner

**Comment by Raghavendra-BJ** [comment]
Hey @anajsana , Help me if my comment is visible now

**Comment by LawrenceHecht** [comment]
@anajsana I am adding a version of this to the questionnaire draft you will see in a day or two.
