### ISSUE TITLE
Add a question about the place of open source compliance check in the organisation

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/osposurvey#101]
A question should be added to “Part 7: Licensing, Compliance and Repos"  about the place of open source compliance check in the organisation:

- Q?: In case your company has several products,  are the software component analyzis of the different products is done in a central place or by the product teams separately?
  - In a central team
  - Separately by every product
  - Parts are in every product, parts in a central team

**Comment by CsatariGergely** [comment]
@LawrenceHecht correct. What I wanted to put there is if the software composition analyzis is done by a central SCM/DevOps team or by the product teams. Maybe this needs some rewording.

**Comment by anajsana** [comment]
Similar question added in the 2022 version: https://github.com/todogroup/osposurvey/blob/main/2022/questions.md
