### ISSUE TITLE
Add a question about the existence of local container build policy

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/osposurvey#102]
A question should be added to “Part 7: Licensing, Compliance and Repos" about the existence of local container build policy.
- Q?: In case your company uses Linux containers, is there a policy to mandate the local building of the used containers
  - Yes
  - Yes, but dependent containers are pulled in binary
  - No

**Comment by LawrenceHecht** [comment]
Worth reviewing this question. I just want to make sure that 1) the wording is good and 2) that we are sure we want to focus on Linux containers.

**Comment by CsatariGergely** [comment]
@LawrenceHecht sure, 1) any feedback on the language is welcome. I'm not a native speaker, so I can use any help :) 2) You mean that we should generalize this to all other packages?

**Comment by LawrenceHecht** [comment]
That was what I meant.
