### ISSUE TITLE
Add a question about the existence of approved container base images

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/osposurvey#103]
A question should be added to “Part 7: Licensing, Compliance and Repos" about the existence of approved container base images
- Q?: In case your company uses Linux containers, do you maintain a list of mandated container base images?
  - Yes
  - No

**Comment by LawrenceHecht** [comment]
A list or "inventory". I like this type of topic. It aligns with "policy", which OSPOs can have an impact on.

**Comment by anajsana** [comment]
Licensing, Compliance and Repos section added in the 2022 version: https://github.com/todogroup/osposurvey/blob/main/2022/questions.md
