### ISSUE TITLE
Add a question: Does your OSPO have an InnerSource team or strategy to drive open source culture within the org?

### ISSUE THREAD

**Issue by anajsana** [todogroup/osposurvey#106]
This question was raised during a Panel discussion about OSPOs and ISPOs at FOSSBackstage: https://pretalx.com/foss-backstage-2022/talk/CWLR83/

Developer Education (educating developers to open source) is a very important task within OSPOs that are in the early stages. Might be interesting to add this question to the upcoming OSPO Survey

**Comment by claredillon** [comment]
Fantastic to see this as a direct result of the panel - thanks @anajsana. The answer/results would be very useful to everyone in InnerSource Commons.

**Comment by LawrenceHecht** [comment]
Can you take the word "team" out of the question?
