### ISSUE TITLE
94.111.46.54 appears twice in CSV

### ISSUE THREAD

**Issue by ronkagan** [todogroup/osposurvey#108]
IP address `94.111.46.54` appears in row 132 and row 426 of https://github.com/todogroup/osposurvey/blob/master/2021/results_2021.csv

**Comment by LawrenceHecht** [comment]
Thanks. This was an oversight. I'm going to keep this in the data set for now just so everyone universally is working with the same data. 

I will be creating an aggregate data set of the key data points that match with the upcoming 2022 survey. With that, I'll purge this record.

**Comment by LawrenceHecht** [comment]
Purge Respondent 12756147327  (Row 132)
