### ISSUE TITLE
Fix answer typo in question 11

### ISSUE THREAD

**Issue by borisbaldassari** [todogroup/osposurvey#112]
In question 11 (`Does your open source program have an InnerSource team or strategy to drive open source culture within the organization?`) the second answer has a typo: `Yes, and we are the strategy has multiple stakeholders` should probably read as `Yes, and the strategy has multiple stakeholders`.

**Comment by LawrenceHecht** [comment]
I fixed this in the documentation, and it will be fixed in the final report.
