### ISSUE TITLE
OSPO Survey 2022 pdf page 24 missing legend

### ISSUE THREAD

**Issue by winterrocks** [todogroup/osposurvey#114]
It seems that on the OSPO Survey 2022 pdf version (https://github.com/todogroup/todogroup.org/files/9557802/OSPOSurveyResults_2022.pdf) page 24 "Consensus about top OSPO responsibilities is greater among North American organizations" the graph is missing the legend. Right side there is a graph that has 13 categories and for each there are 4 pillars (%) and these pillars do not have any legend. 
These pillars are likely regions like they are on page 30:
- Total
- USA & Canada
- Europe
- Asia-Pacific (including Oceania)
But the pillars could be something else, e.g., organization size.

**Comment by anajsana** [comment]
Thanks for reporting this issue @winterrocks !! (cc @LawrenceHecht for awareness)

**Comment by LawrenceHecht** [comment]
thanks. I uploaded a new file to https://github.com/todogroup/osposurvey/blob/main/OSPOSurveyResults_2022-3.pdf.
