### ISSUE TITLE
Add question on the future about companies open sourcing / sharing data

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/osposurvey#70]

**Comment by LawrenceHecht** [comment]
Not addressing this in the 2021 survey.

**Comment by anajsana** [comment]
Is this something we should consider for the 2022 survey?

**Comment by LawrenceHecht** [comment]
I am not privy to strategic discussions, but the topic is still relevant. 
- I believe this topic was originally meant to include all kinds of data, not just metrics related to measuring OSS projects, SBOMs, etc.

**Comment by caniszczyk** [comment]
will close this old issue
