### ISSUE TITLE
Drop the list of companies from Question 32

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/osposurvey#81]
The list of companies in Question 32 inserts bias into the survey that is perpetuated when discussing the survey results. This question should be dropped in favor of a more open-ended  question that doesn't bias the results.

I'm opening this issue in response to how I saw the data from this survey presented by The New Stack at All Things Open 2020. I'll post a link to the recorded talk once it has been posted online, and add additional comments when I can offer screenshots and precise observations.

**Comment by LawrenceHecht** [comment]
See #77 as another approach -- which, I believe was to have a standard set of questions for which any company can benchmark themselves.

**Comment by LawrenceHecht** [comment]
@DuaneOBrien here is the link to what I think you was shared in the presentation (I wasn't actually there): https://thenewstack.io/constructive-open-source-citizenship-produces-results/.

**Comment by DuaneOBrien** [comment]
This question is still part of the survey, and I still believe this question is problematic.

**Comment by caniszczyk** [comment]
@LawrenceHecht can you describe how this was re-written in the draft, I think it's a much better version than what we have

**Comment by LawrenceHecht** [comment]
We added two new questions: "Excluding the aforementioned companies, please nominate up to **three technology or software companies** that exemplify good open source community citizenship..."

Then we ask the same thing about "non-technology or software companies"

We don't need to rate companies.

**Comment by anajsana** [comment]
This issue is from 2020 and was implemented for 2021 survey.
