### ISSUE TITLE
Question 41 is Application focussed

### ISSUE THREAD

**Issue by craigez** [todogroup/osposurvey#88]
There's no equivalent for non-application development organisations, or organisations with mixed deliverables, e.g. some applications/services and some embedded devices with less frequent update cycles. The question is also worded in a way that focusses on web applications/services, i.e. "into production", implying multiple environments that don't exist in all delivery mechanisms.

**Comment by LawrenceHecht** [comment]
This is good feedback on multiple levels. I am not going to make a change. For this study, we will keep the question and compare the change over time. BUT, I recommend that we consult with the authors of the soon to be released study sponsored by the European Commission that focused on Open Source Hardware -- they will have some unique insights into how to come up with a metric that can be used by everyone.
