### ISSUE TITLE
Question 39 unclear what "maintain" means

### ISSUE THREAD

**Issue by craigez** [todogroup/osposurvey#89]
Do we mean this to include projects a company maintainers under their copyright? downstream versions a company maintains? upstream projects in a foundation or other organisation where the company employees act as maintainers? Or are we okay with it being intentionally ambiguous?

**Comment by LawrenceHecht** [comment]
It doesn't have any reference to copyright. The presumption is that if a company is maintaining a project, then the repo is within an "organization" of controlled by the company OR by an employee using a company email address.

**Comment by craigez** [comment]
Should we be more specific then? I'm guessing we are not meaning to count the linux kernel as a project a company maintains just because they have a subsystem maintainer on staff.

> How many open source projects does your company maintain in company controlled organisations or repository hosting environments?

Doesn't sound very good though sorry.

**Comment by LawrenceHecht** [comment]
I'm going to sleep on this.
